// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cheesecake
bool cheesecake(int i);
RcppExport SEXP gluesless_cheesecake(SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    __result = Rcpp::wrap(cheesecake(i));
    return __result;
END_RCPP
}
