// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// run
SEXP run(SEXP modell_builder);
RcppExport SEXP gluesless_run(SEXP modell_builderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type modell_builder(modell_builderSEXP);
    rcpp_result_gen = Rcpp::wrap(run(modell_builder));
    return rcpp_result_gen;
END_RCPP
}
