# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cheesecake!
#'
#' @description
#' test
#'
#' @details
#' test
#'
#' @param i test
#'
#' @return
#' test
#'
#' @examples
#' cheesecake()
#'
#' @export
cheesecake <- function(i = 1L) {
    .Call('gluesless_cheesecake', PACKAGE = 'gluesless', i)
}

#' @export
graphtest <- function() {
    .Call('gluesless_graphtest', PACKAGE = 'gluesless')
}

#' run model
#'
#' @description
#' test
#'
#' @details
#' test
#'
#' @param modell_builder test
#' @param steps test
#'
#' @return
#' test
#'
#' @examples
#' f <- function(size,birthrate,deathrate) {
#'   res <- size + size*birthrate*2 - size*deathrate*2
#'   return(res)
#' }
#'
#' test_builder <- new(
#'   "modell_builder",
#'   pop_size = 200,
#'   pop_birthrate = 0.01,
#'   pop_deathrate = 0.005,
#'   pop_develop_udef_decision = FALSE,
#'   pop_develop_udef = f
#' )
#'
#' run(test_builder)
#'
#' @export
run <- function(modell_builder, steps = 100L) {
    .Call('gluesless_run', PACKAGE = 'gluesless', modell_builder, steps)
}

