# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cheesecake!
#'
#' @description
#' test
#'
#' @details
#' test
#'
#' @param i test
#'
#' @return
#' test
#'
#' @examples
#' cheesecake()
#'
#' @export
cheesecake <- function(i = 1L) {
    .Call('gluesless_cheesecake', PACKAGE = 'gluesless', i)
}

