# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cheesecake!
#'
#' @description
#' test
#'
#' @details
#' test
#'
#' @param i test
#'
#' @return
#' test
#'
#' @examples
#' cheesecake()
#'
#' @export
cheesecake <- function(i = 1L) {
    .Call('gluesless_cheesecake', PACKAGE = 'gluesless', i)
}

#' run model
#'
#' @description
#' test
#'
#' @details
#' test
#'
#' @param popdevel test
#' @param steps test
#'
#' @return
#' test
#'
#' @examples
#' f <- function(size,birthrate,deathrate) {
#'   res <- size + size*birthrate*2 - size*deathrate*2
#'   return(res)
#' }
#'
#' run(f)
#'
#' @export
run <- function(popdevel, steps = 100L) {
    .Call('gluesless_run', PACKAGE = 'gluesless', popdevel, steps)
}

